Derek furst/multipe components
hubmapconsortium/ingest-api pull request #393
Opened 2023-10-10 20:37 UTC by DerekFurstPitt

Implemented multiple components endpoint (companion endpoint to the entity-api components endpoint). Makes a call to entity api's endpoint where all validation is done. If it returns a 200, it uses ingest file helper to create directories for each of the datasets created.

2023-10-17 16:27 UTC, yuanzhou requested changes
@DerekFurstPitt to support this new endpoint, you'll also need to define it in the "old gateway": https://github.com/hubmapconsortium/gateway. Please branch off `main` and PR back to `dev-integrate` with adding the new endpoint to `api_endpoints.<dev|test|stage|prod>.json` file under the ingest-api section. Require the read group `5777527e-ec11-11e8-ab41-0af86edb4424` to pass auth should be fine, the entity-api checks the group write permission with AWS API Gateway more thoroughly in the subsequent call.

2023-10-17 16:27 UTC, yuanzhou commented on src/app.py
> +        elif 'nexus_token' in auth_tokens:
The code is probably copied from the old `POST /datasets` function. As a matter of fact, `nexus_token` had been deprecated by Globus. Just remove this `elif` block here. We don't touch the old code though.

2023-10-17 16:27 UTC, yuanzhou commented on src/app.py
> +            return(Response("Valid nexus auth token required", 401))
Let's use `globus groups token` in the message

2023-10-18 18:14 UTC, DerekFurstPitt commented
@yuanzhou The requested changes have been made, changes from main have been pulled in. After long discussions with @maxsibilla we arrived at how we should handle the symlink stuff. It works in my local testing, but I had to make heavy changes to the request as well as my configs because I don't have a top level /hive/ directory and can't create files off the root like that. I want to test it with the entity-api piece that's on dev to verify that it still works properly.

2023-10-18 19:06 UTC, yuanzhou requested changes
@DerekFurstPitt we only need to do all the `dataset_link_abs_dir` validations upfront before making a call to entity-api. As I think about this endpoint and the one in entity-api a bit more, we don't even need to send over the `dataset_link_abs_dir` field to entity-api and do extra validation there then return it back again. This field is only relevant to ingest-api, entity-api shouldn't even care about it.

@maxsibilla @shirey what do you think?

2023-10-19 14:47 UTC, yuanzhou approved these changes

2023-10-19 14:47 UTC, merged